import json, os

sites_data = []

# Karnataka (10 sites)
sites_data.append(('hampi', 'The Lost Royal Seal', 'Hampi', 'Karnataka', 'Imperial Capital', '14th - 16th Century CE', 8, 'Vijayanagara Royal Seal Bearer', '👑',
 [
     ('Virupaksha Temple', 15.3350, 76.4600, 'I am made of stone and reach toward the sky. I stand at the entrance. What am I?', 'Gopuram', ['tower', 'gopura'], 'Entrance tower', 'What is a gopuram?', ['A temple entrance tower', 'A throne', 'A weapon', 'A market'], 0),
     ('Hampi Bazaar', 15.3340, 76.4635, 'Centuries ago, diamonds were sold in open bowls on my street. What am I called?', 'Bazaar', ['market', 'marketplace'], 'Market street', 'What was traded at Hampi Bazaar?', ['Gemstones and diamonds', 'Plastic toys', 'Coins', 'Cars'], 0),
     ('Vittala Temple & Stone Chariot', 15.3389, 76.4789, 'I have four carved wheels of solid granite, but I never travel an inch. What am I?', 'Stone Chariot', ['chariot', 'ratha'], 'Vehicle of gods', 'Which currency note shows the Hampi Chariot?', ['₹50 Note', '₹10 Note', '₹100 Note', '₹500 Note'], 0),
     ('King\'s Balance (Tulabhara)', 15.3398, 76.4820, 'On special festivals, the king sat on one side of my scale, and gold on the other. What am I?', 'King\'s Balance', ['balance', 'scale'], 'Weighing scale', 'Why did the King weigh himself?', ['To donate gold to the people', 'To check weight', 'To train', 'To buy horses'], 0),
     ('Lotus Mahal', 15.3205, 76.4710, 'My arches open gracefully like the petals of India\'s national flower. What palace am I?', 'Lotus Mahal', ['lotus palace', 'kamal mahal'], 'Pink water flower', 'How was Lotus Mahal kept cool?', ['Water pipes in walls', 'Fans', 'Ice', 'Open roof'], 0),
     ('Elephant Stables', 15.3212, 76.4725, 'I have eleven grand domed rooms. My giant residents had long trunks. What am I?', 'Elephant Stables', ['elephant stable', 'gaja shala'], 'Giant trunk animal', 'How many domed chambers are there?', ['11 Chambers', '5 Chambers', '20 Chambers', '50 Chambers'], 0),
     ('Mahanavami Dibba', 15.3182, 76.4688, 'I am a 12-meter stepped platform where kings celebrated the 10-day victory festival. What am I?', 'Mahanavami Dibba', ['dasara platform', 'dibba'], '9th day festival', 'Which festival was celebrated here?', ['Dasara / Navaratri', 'Holi', 'New Year', 'Kite Day'], 0),
     ('Royal Enclosure Secret Chamber', 15.3168, 76.4675, 'I am the sacred emblem of the Empire with the boar, sun, and moon. What have you found?', 'The Royal Seal', ['royal seal', 'seal'], 'Imperial seal', 'What symbols were on the Royal Seal?', ['Sun and Crescent Moon', 'Two Comets', 'Seven Stars', 'Lightning'], 0)
 ]))

sites_data.append(('mysore-palace', 'The Maharaja\'s Missing Message', 'Mysore Palace', 'Karnataka', 'Royal Palace', 'Wadiyar Dynasty', 6, 'Wadiyar Royal Herald', '💎',
 [
     ('Gombe Thotti (Doll\'s Pavilion)', 12.3051, 76.6552, 'I am a traditional wooden figurine showcased during Dasara. In Kannada my name means doll. What pavilion am I?', 'Gombe Thotti', ['doll pavilion', 'gombe'], 'Kannada for doll', 'What does Gombe mean in Kannada?', ['Doll', 'Sword', 'Elephant', 'Crown'], 0),
     ('Kalyana Mantapa (Marriage Hall)', 12.3053, 76.6554, 'I have eight sides and stained-glass peacock tiles from Scotland. What hall am I?', 'Kalyana Mantapa', ['marriage hall', 'kalyan mantap'], 'Auspicious marriage', 'Which bird is depicted on the stained glass ceiling?', ['Peacock', 'Eagle', 'Parrot', 'Swan'], 0),
     ('Diwan-i-Khas (Private Durbar)', 12.3055, 76.6556, 'I am painted in sea-green turquoise with gilded arches for private royal council. What hall am I?', 'Diwan-i-Khas', ['private durbar', 'diwan khas'], 'Exclusive council', 'What was the purpose of Diwan-i-Khas?', ['Private meetings with ministers', 'Dining', 'Kitchen', 'Barracks'], 0),
     ('Ambavilasa (Public Durbar Hall)', 12.3057, 76.6558, 'I am the grandest public court where the Maharaja sat upon the Golden Throne. What is my name?', 'Ambavilasa', ['durbar hall', 'amba vilasa'], 'Public hall', 'What material covers the ceremonial doors?', ['Solid Carved Silver', 'Plastic', 'Clay', 'Tin'], 0),
     ('The Golden Howdah (Chinnada Ambari)', 12.3050, 76.6550, 'I weigh 750 kilograms of pure gold and ride atop the royal tusker elephant. What am I?', 'Golden Howdah', ['howdah', 'ambari'], 'Elephant throne', 'How much does the Golden Howdah weigh?', ['750 Kilograms', '50 Kilograms', '100 Kilograms', '2000 Kilograms'], 0),
     ('Palace Illumination & Royal Gate', 12.3045, 76.6545, '100,000 of us light up the palace like a glowing dream. What are we?', 'Light Bulbs', ['lights', 'bulbs', 'illumination'], 'Electric lights', 'How many bulbs light up Mysore Palace?', ['Nearly 100,000 bulbs', '500 bulbs', '2000 bulbs', '10000 bulbs'], 0)
 ]))

sites_data.append(('chitradurga-fort', 'The Seven Walls Mystery', 'Chitradurga Fort', 'Karnataka', 'Hill Fortress', 'Nayakas Dynasty', 8, 'Fortress Defender of Chitradurga', '🛡️',
 [
     ('Rangayyana Bagilu (Outer Gate)', 14.2215, 76.3980, 'I am built with winding zig-zag curves so war elephants cannot charge inside. What entrance am I?', 'Rangayyana Bagilu', ['main gate', 'outer gate'], 'Main entrance', 'Why were paths built with zig-zag turns?', ['To stop charging war elephants', 'For hide and seek', 'For wind', 'For art'], 0),
     ('Obavvana Kindi (Heroine\'s Crevice)', 14.2230, 76.3995, 'I defended this narrow rock hole armed only with a wooden rice pestle (Onake). Who am I?', 'Onake Obavva', ['obavva', 'heroine'], 'Brave woman warrior', 'What tool did Onake Obavva use to defend the fort?', ['A wooden rice pestle (Onake)', 'A bronze spoon', 'A stone hammer', 'A shield'], 0),
     ('Ekanatheshwari Temple', 14.2245, 76.4010, 'I am the patron goddess temple of the fortress nestled against huge granite boulders. What temple am I?', 'Ekanatheshwari Temple', ['ekanatheshwari', 'temple'], 'Patron shrine', 'How many temples were built inside the fort?', ['18 Temples', '2 Temples', '5 Temples', '50 Temples'], 0),
     ('Hidimbeshwara Cave Temple', 14.2255, 76.4020, 'Carved directly from a natural boulder, I am named after an epic Mahabharata character. What cave temple am I?', 'Hidimbeshwara Temple', ['hidimbeshwara', 'cave'], 'Epic hero cave', 'From which epic does Hidimbeshwara originate?', ['Mahabharata', 'Ramayana', 'Panchatantra', 'Jataka'], 0),
     ('Gunpowder Mills (Maddu Bisuva Kallu)', 14.2260, 76.4035, 'I have four giant round stones used to grind cannon powder. What am I?', 'Gunpowder Mill', ['gun powder mill', 'mill'], 'Ammunition grinder', 'What was manufactured at these grinding mills?', ['Gunpowder for cannons', 'Flour for bread', 'Sugar', 'Spices'], 0),
     ('Rainwater Harvesting Tanks (Honda)', 14.2270, 76.4045, 'I am a carved stone pond that captured every drop of rain so soldiers never went thirsty. What am I?', 'Rainwater Tank', ['honda', 'water tank'], 'Rain harvest pond', 'How many water tanks supplied the fort garrison?', ['Over 35 Reservoirs', 'Only 1 Tank', '5 Tanks', 'None'], 0),
     ('The Summit Watch Tower (Gali Gopura)', 14.2280, 76.4060, 'Perched on the highest cliff, my name means Wind Tower. Sentinels watched for enemy flags. What tower am I?', 'Gali Gopura', ['wind tower', 'watch tower'], 'Wind tower', 'What does the Kannada word Gali mean?', ['Wind', 'Sun', 'Stone', 'Fire'], 0),
     ('The Seventh Citadel Wall', 14.2290, 76.4075, 'I am the final, seventh circular wall enclosing the highest kingly citadel. What mystery have you solved?', 'The Seven Walls', ['seven walls', 'yelu suttina kote'], 'Seven defense rings', 'How were the fort stones held together?', ['Interlocking precision joints without cement', 'Mud glue', 'Wood nails', 'Tape'], 0)
 ]))

sites_data.append(('badami-caves', 'The Cave Sculptor\'s Secret', 'Badami Cave Temples', 'Karnataka', 'Rock-Cut Temples', 'Chalukya Dynasty', 6, 'Chalukya Master Carver', '⛏️',
 [
     ('Cave 1: Dancing Nataraja', 15.9180, 75.6765, 'I am the cosmic dancer with eighteen carved stone arms depicting Bharatanatyam poses. Who am I?', 'Nataraja', ['shiva', 'dancing shiva'], 'Cosmic dancer', 'How many arms does Nataraja have in Cave 1?', ['18 Arms', '4 Arms', '8 Arms', '100 Arms'], 0),
     ('Cave 2: Trivikrama Cosmic Strides', 15.9185, 75.6772, 'I stepped across the earth with one foot and the sky with my second foot. What avatar am I?', 'Trivikrama', ['vamana', 'vishnu'], 'Three cosmic strides', 'Which avatar of Vishnu measured the cosmos?', ['Trivikrama (Vamana)', 'Matsya', 'Kurma', 'Rama'], 0),
     ('Cave 3: Narasimha & Harihara', 15.9190, 75.6780, 'I am the largest and most grandly carved cave in Badami with an inscription from 578 CE. What cave am I?', 'Cave 3', ['cave three', '3'], 'Third cave', 'In which century was Cave 3 dedicated?', ['6th Century CE (578 CE)', '12th Century CE', '1st Century BCE', '20th Century'], 0),
     ('Cave 4: Mahavira & Jain Tirthankaras', 15.9195, 75.6788, 'I am the 24th Tirthankara seated serenely on a lion throne. Who am I?', 'Mahavira', ['lord mahavira'], 'Jain teacher', 'Whom is Cave 4 dedicated to?', ['Jain Tirthankaras (Mahavira)', 'Greek philosophers', 'Roman kings', 'Pharaohs'], 0),
     ('Agastya Lake', 15.9200, 75.6795, 'I am the sacred lake nestled in the red sandstone canyon between the cave cliffs. What lake am I?', 'Agastya Lake', ['agastya lake', 'lake'], 'Sage water lake', 'Who was the lake at Badami named after?', ['Sage Agastya', 'Alexander', 'Marco Polo', 'Vasco da Gama'], 0),
     ('Bhootnath Temple at Water\'s Edge', 15.9208, 75.6810, 'I sit right on the water edge of the lake with my reflection shimmering on the waves. What temple am I?', 'Bhootnath Temple', ['bhootnath', 'bhutanatha'], 'Water edge temple', 'Where is Bhootnath Temple located?', ['Directly at the water edge of Agastya Lake', 'Underground', 'On a plane', 'On a glacier'], 0)
 ]))

sites_data.append(('aihole', 'The Ancient Architect', 'Aihole', 'Karnataka', 'Temple Laboratory', '5th - 8th Century CE', 6, 'Master Architect Apprentice', '📐',
 [
     ('Durga Temple (Apsidal Wonder)', 16.0195, 75.8820, 'I have a rounded apsidal back like a horseshoe or Buddhist chaitya hall. What temple am I?', 'Durga Temple', ['durga', 'durga temple aihole'], 'Fortress temple', 'Why is it called the Durga Temple?', ['It was located near the fort (Durg) wall', 'It was green', 'It was a ship', 'It had 100 doors'], 0),
     ('Lad Khan Temple', 16.0190, 75.8815, 'I resemble a village meeting hall with stone lattice windows and a roof shrine. What temple am I?', 'Lad Khan Temple', ['lad khan', 'ladkhan'], 'Oldest stone shrine', 'What architectural feature filters sunlight?', ['Carved stone lattice (Jali) windows', 'Glass', 'Mirrors', 'Curtains'], 0),
     ('Ravana Phadi Cave', 16.0210, 75.8845, 'I am Aihole\'s oldest rock-cut cave, famous for my 10-armed Dancing Shiva relief. What cave am I?', 'Ravana Phadi', ['ravana phadi', 'ravanaphadi'], 'Rock-cut cave', 'Approximately when was Ravana Phadi carved?', ['550 CE (6th Century)', '1800 CE', '200 BCE', '1950 CE'], 0),
     ('Meguti Jain Temple & Inscription', 16.0225, 75.8860, 'My stone wall carries the famous 634 CE poem praising the victories of King Pulakeshin II. What temple am I?', 'Meguti Temple', ['meguti', 'meguti jain temple'], 'Hilltop temple', 'Which northern emperor was defeated by Pulakeshin II?', ['Emperor Harsha', 'Alexander', 'Caesar', 'Genghis Khan'], 0),
     ('Huchappayyagudi Temple', 16.0180, 75.8800, 'I feature exquisite ceiling carvings of Garuda and celestial deities soaring in flight. What temple am I?', 'Huchappayyagudi', ['huchappayya', 'huchappayyagudi temple'], 'Ceiling art temple', 'Where are the flying deity carvings located?', ['On the stone ceiling panels', 'In a well', 'On roof tiles', 'On grass'], 0),
     ('Konti Gudi Group', 16.0175, 75.8790, 'We are a cluster of four ancient shrines representing the experimental cradle of temple architecture. What are we?', 'Konti Gudi', ['konti gudi', 'kontigudi'], 'Cradle cluster', 'What title is Aihole famously known by?', ['The Cradle of Indian Temple Architecture', 'Golden City', 'Desert Oasis', 'Mountain Peak'], 0)
 ]))
sites_data = []
