from gen_hunts import cp

def get_karnataka_sites():
    return [
        {
            'id': 'hampi', 'title': 'The Lost Royal Seal', 'siteName': 'Hampi', 'state': 'Karnataka',
            'category': 'Imperial Capital', 'era': '14th - 16th Century CE (Vijayanagara Empire)',
            'heroImage': 'https://images.unsplash.com/photo-1600100397608-f010f443b74d?auto=format&fit=crop&w=1200&q=80',
            'description': 'A royal seal belonging to the Vijayanagara Empire has been lost. A royal messenger left clues around the ancient city. Explore Hampi, solve the clues and recover the seal.',
            'difficulty': 'Explorer (Kids & Family)', 'estimatedDuration': '45 mins', 'totalCheckpoints': 8,
            'badgeReward': {'name': 'Vijayanagara Royal Seal Bearer', 'icon': '👑', 'description': 'Discovered the Lost Royal Seal of Vijayanagara in Hampi!'},
            'checkpoints': [
                cp('HAMPI_001', 1, 'Virupaksha Temple', 15.3350, 76.4600, 60,
                   'Your first clue is waiting at one of Hampi\'s most important temples where stone tells stories and towers kiss the sky.',
                   'Look towards the soaring gateway tower where bells chime and sacred waters flow.',
                   'Look carefully at the temple entrance. Can you find decorative figures carved into the structure?',
                   'I am made of stone and reach toward the sky. I stand at the entrance and can be seen from far away. What am I?',
                   'Gopuram', ['tower', 'temple tower', 'gopura', 'entrance tower'],
                   'I am the grand, pyramid-shaped tower right above the main entrance gate.', 'My name starts with G and rhymes with forum: G _ _ _ _ _ M.',
                   'A gopuram is a large monumental entrance tower commonly found at South Indian temples. Virupaksha\'s tower rises 50 meters high!',
                   'What is a gopuram?', ['A temple entrance tower', 'A royal throne', 'A type of weapon', 'A marketplace'], 0),
                cp('HAMPI_002', 2, 'Hampi Bazaar', 15.3340, 76.4635, 70,
                   'The royal messenger walked down this wide street where merchants once traded glittering diamonds, silks, and sweet spices.',
                   'Walk along the stone pavilions that once bustled with ruby and diamond merchants.',
                   'Observe the long colonnades of stone pillars lining both sides of the ancient street.',
                   'Centuries ago, diamonds and pearls were sold by the bowl on my street. I am a grand open marketplace. What am I called?',
                   'Bazaar', ['market', 'hampi bazaar', 'marketplace'],
                   'It is an ancient word for a shopping street or market area.', 'It begins with B: B _ Z _ _ R.',
                   'During the 15th century, foreign travelers wrote in wonder about precious gems sold in open baskets along this 800-meter street.',
                   'What precious items were famously traded in open bowls at Hampi Bazaar?', ['Gemstones and diamonds', 'Plastic toys', 'Modern coins', 'Chips'], 0),
                cp('HAMPI_003', 3, 'Vittala Temple & Stone Chariot', 15.3389, 76.4789, 60,
                   'The messenger hid the next clue near an incredible shrine shaped like a vehicle of the gods with carved granite wheels.',
                   'Find the iconic stone vehicle in the courtyard that looks ready to roll across the heavens.',
                   'Find the giant stone wheels of the chariot and spot the elephants standing guard.',
                   'I have four carved wheels made of solid granite, but I never travel an inch. What monument am I?',
                   'Stone Chariot', ['chariot', 'vittala chariot', 'ratha'],
                   'You can find me right inside the courtyard of the famous Vittala Temple.', 'I look like a royal chariot carved out of stone.',
                   'The Stone Chariot is dedicated to Garuda and is featured on the Indian 50 Rupee currency note!',
                   'Which Indian rupee currency note features the iconic Hampi Stone Chariot?', ['₹50 Note', '₹10 Note', '₹100 Note', '₹500 Note'], 0),
                cp('HAMPI_004', 4, 'King\'s Balance (Tulabhara)', 15.3398, 76.4820, 50,
                   'Find the two tall granite pillars where emperors once weighed themselves in pure gold to donate to the people.',
                   'Search near the riverbank for a giant stone archway with ring hooks at the top.',
                   'Look up at the stone crossbar where the giant scales once hung.',
                   'On special festivals, the king sat on one side of my scale, while gold, silver, and jewels were placed on the other. What am I?',
                   'King\'s Balance', ['kings balance', 'balance', 'scale', 'tulabhara'],
                   'It looks like a giant stone weighing scale archway.', 'Its name includes the words King and Balance.',
                   'This ritual was called Tulapurusha Dana. Kings weighed themselves against gold on coronation days.',
                   'Why did the Emperor weigh himself on the King\'s Balance?', ['To donate equal weight of gold to the people', 'To check weight', 'To measure cannonballs', 'To buy horses'], 0),
                cp('HAMPI_005', 5, 'Lotus Mahal', 15.3205, 76.4710, 50,
                   'The messenger left a scroll inside a delicate summer palace shaped like an opening flower bud, cooled by ancient water pipes.',
                   'Discover the elegant two-story pavilion with curved multi-fold cusped arches.',
                   'Look at the graceful petal-like archways and lotus bud carvings on the ceiling.',
                   'My arches open gracefully like the petals of India\'s national flower. I kept queens cool in summer. What palace am I?',
                   'Lotus Mahal', ['lotus palace', 'kamal mahal', 'lotus'],
                   'I am named after a sacred pink flower that grows on water.', 'L _ _ _ S  M _ _ _ L.',
                   'The Lotus Mahal had built-in water pipes inside its walls to act like ancient air conditioning during hot summers!',
                   'How was the Lotus Mahal kept cool naturally during hot summers?', ['Water pipes inside walls cooled circulating air', 'Electric ceiling fans', 'Imported ice', 'Open roof'], 0),
                cp('HAMPI_006', 6, 'Elephant Stables', 15.3212, 76.4725, 60,
                   'The next clue rests where eleven grand domed suites housed the emperor\'s mighty royal pachyderms.',
                   'Locate the long symmetrical building with 11 distinct dome roofs in a row.',
                   'Find the iron hooks in the ceilings where royal elephants were tied with silk ropes.',
                   'I have eleven grand domed rooms. My gentle giant residents had long trunks and large ears. What building am I?',
                   'Elephant Stables', ['elephant stable', 'elephant', 'gaja shala'],
                   'The largest land animal with a trunk lived here in luxury.', 'E _ _ _ _ _ _ T  S _ _ _ _ _ S.',
                   'The eleven domed chambers housed the Emperor\'s personal ceremonial elephants with different architectural dome shapes.',
                   'How many domed chambers make up the famous Elephant Stables of Hampi?', ['11 Chambers', '5 Chambers', '20 Chambers', '50 Chambers'], 0),
                cp('HAMPI_007', 7, 'Mahanavami Dibba', 15.3182, 76.4688, 60,
                   'Climb the highest stone platform in the Royal Enclosure where kings watched grand Dasara parades.',
                   'Step up the massive three-tier granite platform carved with marching hunters and dancers.',
                   'Inspect the bottom carved tier showing relief carvings of foreign ambassadors.',
                   'I am a 12-meter high stepped stone platform where kings celebrated the 10-day Dasara festival. What is my name?',
                   'Mahanavami Dibba', ['navami dibba', 'dasara platform', 'dibba'],
                   'The name refers to the great 9th/10th day festival of Navaratri / Mahanavami.', 'M _ _ _ N _ _ _ M I   D _ _ _ A.',
                   'Mahanavami Dibba offers a 360-degree command view over the entire royal city!',
                   'Which grand 10-day festival was celebrated at Mahanavami Dibba?', ['Dasara / Navaratri Festival', 'Holi Festival', 'New Year Eve', 'Kite Flying Day'], 0),
                cp('HAMPI_008', 8, 'Royal Enclosure & Stepped Tank', 15.3168, 76.4675, 50,
                   'Beside the geometric black schist Stepped Tank lies the underground chamber where the Lost Royal Seal is preserved.',
                   'Look for the perfectly symmetrical black schist stepped tank resembling an inverted pyramid.',
                   'Observe the remarkable geometric staircases leading down to the water.',
                   'I am the sacred emblem of the Vijayanagara Empire, stamped on gold coins with the boar, sun, and moon. What have you discovered?',
                   'The Royal Seal', ['royal seal', 'seal', 'vijayanagara seal', 'varaha seal'],
                   'It is the ultimate imperial artifact you have been hunting for!', 'R _ _ _ L   S _ _ L.',
                   'Congratulations Explorer! The Vijayanagara royal seal depicted the Varaha boar with the sun and moon, symbolizing strength and justice.',
                   'What celestial symbols were carved onto the Vijayanagara Royal Seal?', ['Sun and Crescent Moon', 'Two Comets', 'Seven Stars', 'Lightning'], 0, 100, 200)
            ]
        },
        {
            'id': 'mysore-palace', 'title': 'The Maharaja\'s Missing Message', 'siteName': 'Mysore Palace', 'state': 'Karnataka',
            'category': 'Royal Palace', 'era': 'Wadiyar Dynasty (1912 CE)',
            'heroImage': 'https://images.unsplash.com/photo-1580181651977-398f5f0c02c0?auto=format&fit=crop&w=1200&q=80',
            'description': 'The Maharaja of Mysore left a coded royal proclamation hidden in the palace corridors. Decode the clues to reveal the message of wisdom.',
            'difficulty': 'Explorer (Kids & Family)', 'estimatedDuration': '40 mins', 'totalCheckpoints': 6,
            'badgeReward': {'name': 'Wadiyar Royal Herald', 'icon': '💎', 'description': 'Decoded the Maharaja\'s Missing Message at Mysore Palace!'},
            'checkpoints': [
                cp('MYS_001', 1, 'Gombe Thotti (Doll\'s Pavilion)', 12.3051, 76.6552, 40,
                   'Begin at the entrance gallery filled with traditional dolls and the ceremonial wooden elephant howdah.',
                   'Enter through the pavilion where colorful Dasara dolls greet visiting dignitaries.',
                   'Look for the wooden howdah model and carved palanquins on display.',
                   'I am a traditional wooden figurine showcased during Dasara. In Kannada my name means doll. What pavilion am I?',
                   'Gombe Thotti', ['doll pavilion', 'dolls pavilion', 'gombe'],
                   'In Kannada, Gombe means Doll.', 'G _ _ B E   T _ _ T T I.',
                   'Gombe Thotti is the entrance gallery to the palace displaying traditional dolls during Dasara.',
                   'What does the Kannada word Gombe mean?', ['Doll', 'Sword', 'Elephant', 'Crown'], 0),
                cp('MYS_002', 2, 'Kalyana Mantapa (Marriage Hall)', 12.3053, 76.6554, 40,
                   'Step inside the breathtaking octagonal hall under a grand stained-glass dome adorned with peacocks.',
                   'Look up at the multi-colored glass ceiling that paints rainbow patterns on the floor.',
                   'Count the vibrant peacock motifs spread across the glass canopy.',
                   'I have eight sides, peacock tiles from England, and iron pillars from Scotland. What hall am I?',
                   'Kalyana Mantapa', ['marriage hall', 'marriage pavilion', 'kalyan mantap'],
                   'Kalyana means auspicious marriage or wedding.', 'K _ _ Y _ N A   M _ N _ _ P A.',
                   'The stained glass ceiling was crafted in Glasgow, Scotland, and the floor features glazed peacock mosaic tiles.',
                   'Which bird is depicted across the stained glass ceiling of Kalyana Mantapa?', ['Peacock', 'Eagle', 'Parrot', 'Swan'], 0),
                cp('MYS_003', 3, 'Diwan-i-Khas (Private Durbar)', 12.3055, 76.6556, 40,
                   'Walk between turquoise and gold cast-iron arches where the Maharaja held private consultations.',
                   'Find the hall glowing in sea-green turquoise pillars and golden flourishes.',
                   'Observe the ornate gold leaf ceiling paintings overlooking Chamundi Hills.',
                   'I am painted in sea-green turquoise with gilded arches. Only trusted ministers entered my council room. What hall am I?',
                   'Diwan-i-Khas', ['diwan i khas', 'private durbar hall', 'diwan khas'],
                   'Khas means exclusive or private.', 'D _ W _ N - I - K _ _ S.',
                   'The turquoise pillars were fabricated in cast iron in the Saracenic style, creating an open airy hall.',
                   'What was the primary purpose of Diwan-i-Khas?', ['Private meetings with ministers', 'Dining hall', 'Kitchen', 'Barracks'], 0),
                cp('MYS_004', 4, 'Ambavilasa (Public Durbar)', 12.3057, 76.6558, 40,
                   'The most opulent room opens before you with crystal chandeliers and solid silver doorways.',
                   'Step into the colossal ceremonial hall overlooking the courtyard.',
                   'Look at the solid silver doors engraved with the ten avatars of Vishnu.',
                   'I am the grandest public court where the Maharaja sat upon the Golden Throne during Dasara. What is my name?',
                   'Ambavilasa', ['amba vilasa', 'public durbar hall', 'durbar hall'],
                   'It starts with Amba and ends with vilasa.', 'A _ B A _ I L _ S A.',
                   'The Durbar Hall features a magnificent gilded coffered ceiling and Scottish iron pillars painted with gold leaf.',
                   'What material covers the ceremonial doors in the Durbar Hall?', ['Solid Carved Silver', 'Plastic', 'Clay', 'Tin'], 0),
                cp('MYS_005', 5, 'The Golden Howdah (Chinnada Ambari)', 12.3050, 76.6550, 40,
                   'The fifth clue is hidden near the legendary elephant throne crafted from 750 kilograms of pure gold.',
                   'Search for the golden seat mounted atop the lead elephant during the Jamboo Savari.',
                   'Observe the intricate filigree and floral engravings on the gold canopy.',
                   'I weigh 750 kilograms of shimmering pure gold and ride atop the royal tusker elephant. What am I?',
                   'Golden Howdah', ['howdah', 'ambari', 'chinnada ambari'],
                   'It is a royal seat placed on the back of an elephant.', 'G _ L _ E N   H _ W D _ H.',
                   'The Golden Howdah weighs 750 kg of pure gold. During Dasara, the idol of Goddess Chamundeshwari is carried inside.',
                   'How much does the Golden Howdah of Mysore weigh?', ['750 Kilograms', '50 Kilograms', '100 Kilograms', '2000 Kilograms'], 0),
                cp('MYS_006', 6, 'Palace Illumination & Royal Gate', 12.3045, 76.6545, 50,
                   'Under the glow of 100,000 bulbs, the message is revealed: Nahi Jnanena Sadrusam (Wisdom is the Greatest Wealth).',
                   'Stand outside the grand arched gateway where thousands of golden lights illuminate the night.',
                   'Count the glowing archways around the perimeter gardens of the palace.',
                   'On Sunday evenings and Dasara nights, 100,000 of us light up the palace like a golden dream. What are we?',
                   'Light Bulbs', ['lights', 'bulbs', 'illumination', 'electric lights'],
                   'We are incandescent electric bulbs illuminating the facade.', 'L _ _ _ T   B _ L _ S.',
                   'Nearly 100,000 bulbs illuminate Mysore Palace simultaneously, powered by a dedicated generator system!',
                   'Approximately how many bulbs illuminate Mysore Palace on festive nights?', ['Nearly 100,000 bulbs', '500 bulbs', '2,000 bulbs', '10,000 bulbs'], 0, 100, 200)
            ]
        }
    ]

print('build_karnataka_sites.py written.')
